### ISSUE TITLE
html_permalinks_icon key error in GitHub pages builds

### ISSUE THREAD

**Issue by jack89roberts** [matplotlib/mpl-third-party#121]
Since #112 it looks like the GitHub pages builds have been failing with a `html_permalinks_icon` key error (which means the last 4 tools to be merged (microfilm, tueplots, grplot and distinctipy) are not appearing on the docs page.

E.g. see this latest build: https://github.com/matplotlib/mpl-third-party/runs/7224799482?check_suite_focus=true

```
Exception occurred:
  File "/usr/local/lib/python3.8/site-packages/pydata_sphinx_theme/__init__.py", line 45, in update_config
    icon_default = app.config.values["html_permalinks_icon"]
KeyError: 'html_permalinks_icon'
The full traceback has been saved in /tmp/sphinx-err-kzajtp7a.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
make: *** [Makefile:21: html] Error 2
Traceback (most recent call last):
  File "/entrypoint.py", line 22, in <module>
    action.build_all_docs(github_env, [os.environ.get("INPUT_DOCS-FOLDER")])
  File "/sphinx_action/action.py", line 167, in build_all_docs
    raise RuntimeError("Build failed")
RuntimeError: Build failed
```

**Comment by jklymak** [comment]
I don't think I set that action up, but if I did, I would have just googled for it - if there is some more apropos action we should use that instead.

**Comment by QuLogic** [comment]
I would do the same; it appears to be the top Google result. I don't know if there are any better alternatives.

Though I guess another alternative is to just do it manually; `setup-python` action + `pip install` which _should_ work, I think?

**Comment by QuLogic** [comment]
> Though I guess another alternative is to just do it manually; `setup-python` action + `pip install` which _should_ work, I think?

It's only 3 steps, so I just went ahead and did that in #123
