### ISSUE TITLE
Switch to a single packages.yml

### ISSUE THREAD

**Issue by timhoffm** [matplotlib/mpl-third-party#129]
Currently, we have a packages folder with one one file per package.

I propose to put everything together into a single YAML file, that contains a list of all the package infos.

It's easier to add new entries if you can see how the others look like. Also it's checking consistency (e.g. section names) is a bit simpler in a single file.

**Comment by story645** [comment]
I think it's harder when you have to add to an existing file cause you have to figure out where to place it in the file & make sure not to mess up any existing formatting & it can be hard to find later to edit. Also I think there's an increased risk of a merge conflict when we have multiple PRs going. 

How much of the consistency can we programmatically check via a custom lint file or the like?

**Comment by timhoffm** [comment]
I'm not following the argument that editing an existing file is harder for the simple yaml structure we have. And merge conflicts are also a more theoretical issue as we should be able to merge such PRs very quickly.

OTOH,  this is not important enough to fight about. So closing.
