### ISSUE TITLE
Layout improvements

### ISSUE THREAD

**Issue by anntzer** [matplotlib/mpl-third-party#24]
The relatively small fixed column width for the badges makes them awkwardly sized (the text size is different if the version is long).  I realize that the full column width is smaller than at https://pyviz.org/tools.html which constrains things, but perhaps you could drop the "Name/Description/Github/..." headers and go for a 2-line-per-project layout?
```
Name <tab> Description (more likely to fit in a single line now as well)
    (github badge) (pypi badge) (conda badge)
```
possibly keeping a blank if there's no pypi badge so that conda badges stay aligned.

**Comment by jklymak** [comment]
I tried that, and it didn't work for me, with my minimal html skills.  But I'd be happy for that change if someone wanted to give it a shot.

**Comment by anntzer** [comment]
(I'm not claiming any web layout expertise either :-))

**Comment by jklymak** [comment]
I think this is OK now.
