### ISSUE TITLE
factor out yaml validation

### ISSUE THREAD

**Issue by story645** [matplotlib/mpl-third-party#42]
Would be useful to have a script `./valid package.yml` folks could run locally on the yml files they're contributing rather than having to wait for the CI. Or to set this up as a standalone github action when new .yml files in package are contributed. 

Either way, would require refactoring the  parsing code in `build.py` into a function that could either be called in the loop in `build.py` or in a standalone script.

**Comment by QuLogic** [comment]
As part of #151, I wrote a small schema for the YAML files. I think we should enable pre-commit and add YAML schema validation to it.
