### ISSUE TITLE
No sure where to list a related package

### ISSUE THREAD

**Issue by PySimpleGUI** [matplotlib/mpl-third-party#60]
Saw the suggestion in this Tweet to let you know about 3rd party packages

![image](https://user-images.githubusercontent.com/46163555/119261646-55993000-bba6-11eb-8d1c-e77bb3b89d2c.png)

For quite some time, PySimpleGUI has integrated with matplotlib.  There are currently 13 "Demo Programs" that help users get a jump start on adding a GUI to their matplotlib programs.

![image](https://user-images.githubusercontent.com/46163555/119261688-82e5de00-bba6-11eb-9123-c20c6f624599.png)

Here's one that shows a number of sample graphs from the matplotlib gallery page.

![image](https://user-images.githubusercontent.com/46163555/119261704-91cc9080-bba6-11eb-9769-217e835b61d4.png)

Others spotlight how little code is needed to make a plot.

![image](https://user-images.githubusercontent.com/46163555/119261813-0b647e80-bba7-11eb-88b6-84a230dc7498.png)

Not sure where to put information like this on this GitHub site.  Maybe you can help?

**Comment by jklymak** [comment]
You can add a file `packages/PySimpleGui.yml`

**Comment by story645** [comment]
And while PySimpleGui is not a rendering backend, that's probably the section with the closest fit (or gui applications)

**Comment by PySimpleGUI** [comment]
Yea, not a rendering backend as I can work with multiple frameworks, not just tkinter.  I'm more of a front-end if such a thing exists in your categories.

**Comment by story645** [comment]
either gui applications or miscellanous

**Comment by PySimpleGUI** [comment]
Thank you!  
"GUI Applications for 100"

**Comment by story645** [comment]
So following up, @PySimpleGUI can you please open a PR adding yourself to the repo? instructions are at https://github.com/matplotlib/mpl-third-party

**Comment by PySimpleGUI** [comment]
Okey dokey!  Sorry that it took a minute, but I got it done.

**Comment by story645** [comment]
Awesome!

**Comment by PySimpleGUI** [comment]
Thank you so much for your patience and help!  Greatly appreciated.  Sorry I was sloppy with things despite the well-written instructions.  BTW, I tried the "Add file" approach, but found that technique doesn't work now.

**Comment by story645** [comment]
Nothing to apologize for & thanks for the suggested improvements!
