### ISSUE TITLE
mpl navigation links

### ISSUE THREAD

**Issue by zmoon** [matplotlib/mpl-third-party#98]
Currently they don't work if on <https://matplotlib.org/mpl-third-party/>, which is too bad. Also I noticed one name is different compared to the mpl 3.5 docs ("User guide" vs "Usage guide"). And Sphinx major version in the published build is 2 behind that used in the mpl docs according to the footer.

**Comment by jklymak** [comment]
Thanks for the report.  For some reason the logic in mpl-sphinx-theme to activate the fixed links is no longer working.

**Comment by jklymak** [comment]
This is fixed now.  Thanks for letting us know!
